### ISSUE TITLE
unpack method in release 0.3.0 returning an error with redis Redis 3.0.2 

### ISSUE THREAD

**Issue by danielgpm** [antirez/lua-cmsgpack#46]
While unpacking a simple lua table returned by a redis script, the method is returning: [error] 5906#0: *1 lua entry thread aborted: runtime error: Bad data format in input.
stack traceback:
coroutine 0:
	[C]: in function 'unpack'
I had to rollback to redis 3.0.1 to fix my environment.
Any plans to publish a new release (0.4.0?) compatible with the latest version of redis? 
Thanks in advance...

**Comment by antirez** [comment]
Sure, for the 0.3.0 versions I uploaded it via LuaRocks in some way:

https://luarocks.org/modules/luarocks

Now I'm no longer sure how to update the package, and a quick search did not helped me. Please could you help me? Thanks.

**Comment by antirez** [comment]
Fixed, thanks.

**Comment by danielgpm** [comment]
Confirmed. It's working fine with 0.4.0, thank you.

**Comment by antirez** [comment]
Great, thanks for the acknowledge.
